"""followers

Revision ID: 777c23b3d2b6
Revises: 2d4e627dac73
Create Date: 2019-03-04 20:20:48.557932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '777c23b3d2b6'
down_revision = '2d4e627dac73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
